name: Gradle CI Bot build

on:
  push:
    branches: [ main, master ]
    paths:
      - "src/**/*"
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Bot build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set-up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle perms
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build